// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalLinkController from "./modal_link_controller"
application.register("modal-link", ModalLinkController)

import PlayerChartController from "./player_chart_controller"
application.register("player-chart", PlayerChartController)
