// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ModalLinkController from "controllers/modal_link_controller"
application.register("modal-link", ModalLinkController)

import PlayerChartController from "controllers/player_chart_controller"
application.register("player-chart", PlayerChartController)

import PushNotificationController from "controllers/push_notification_controller"
application.register("push-notification", PushNotificationController)
