source 'https://rubygems.org'

ruby '2.0.0'
gem 'rails', '4.0.0'

gem 'awesome_print'
gem 'chartkick'
gem 'coffee-rails', '~> 4.0.0'
gem 'dalli'
gem 'devise', '~> 3.0.0.rc'
gem 'draper'
gem 'icalendar'
gem 'ice_cube'
gem 'haml-rails'
gem 'jquery-rails'
gem 'less-rails'
gem 'memcachier'
gem 'pg'
gem 'queue_classic'
gem 'rails_12factor'
gem 'rack-cache'
gem 'sass-rails',   '~> 4.0.0'
gem 'sextant'
gem 'therubyracer'
gem 'thin'
gem 'turbolinks'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '~> 2.1.1'
gem 'unicorn'

group :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'simplecov', require: false
end
