development:
  adapter: postgresql
  encoding: unicode
  database: ultimate_development
  username: ultimate
  password:
  pool: 5
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: ultimate_test
  username: ultimate
  password:
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: ultimate
  username: ultimate
  password: "QfkF@46TtXL6aygB;=rWg?8x"
  pool: 5
  min_messages: WARNING
